Repository codestates-seb/seb45_main_022, pull requests merged in 2023-08, with the labels that each got.

#3 ✨ feat: JWT, Ouath2, 추가
  Server/build.gradle
  Server/src/main/java/com/codestatus/auth/config/PasswordEncoderConfig.java
  Server/src/main/java/com/codestatus/auth/config/SecurityConfig.java
  Server/src/main/java/com/codestatus/auth/dto/LoginDto.java
  Server/src/main/java/com/codestatus/auth/dto/PrincipalDto.java
  Server/src/main/java/com/codestatus/auth/filter/JwtAuthenticationFilter.java
  Server/src/main/java/com/codestatus/auth/filter/JwtVerificationFilter.java
  Server/src/main/java/com/codestatus/auth/handler/MemberAccessDeniedHandler.java
  Server/src/main/java/com/codestatus/auth/handler/MemberAuthenticationEntryPoint.java
  Server/src/main/java/com/codestatus/auth/handler/MemberAuthenticationFailureHandler.java
  Server/src/main/java/com/codestatus/auth/handler/MemberAuthenticationSuccessHandler.java
  Server/src/main/java/com/codestatus/auth/handler/OAuth2MemberSuccessHandler.java
  Server/src/main/java/com/codestatus/auth/jwt/JwtTokenizer.java
  Server/src/main/java/com/codestatus/auth/userdetails/UsersDetailService.java
  Server/src/main/java/com/codestatus/auth/utils/CustomAuthorityUtils.java
  Server/src/main/java/com/codestatus/auth/utils/ErrorResponseSender.java
  Server/src/main/java/com/codestatus/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/response/ErrorResponse.java
  Server/src/main/java/com/codestatus/user/entity/User.java
  Server/src/main/java/com/codestatus/user/repository/UserRepository.java
  Server/src/main/java/com/codestatus/user/service/UserService.java
  Server/src/main/resources/application.yml
Labels: ✨ 기능 추가

#27 ✨ feat: user api 일부 완성
  Server/src/main/java/com/codestatus/advice/GlobalExceptionAdvice.java
  Server/src/main/java/com/codestatus/auth/config/SecurityConfig.java
  Server/src/main/java/com/codestatus/auth/filter/JwtAuthenticationFilter.java
  Server/src/main/java/com/codestatus/auth/userdetails/UsersDetailService.java
  Server/src/main/java/com/codestatus/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/status/entity/Stat.java
  Server/src/main/java/com/codestatus/status/entity/Status.java
  Server/src/main/java/com/codestatus/status/repository/StatRepository.java
  Server/src/main/java/com/codestatus/status/repository/StatusRepository.java
  Server/src/main/java/com/codestatus/user/controller/UserController.java
  Server/src/main/java/com/codestatus/user/dto/StatusResponse.java
  Server/src/main/java/com/codestatus/user/dto/UserDto.java
  Server/src/main/java/com/codestatus/user/entity/User.java
  Server/src/main/java/com/codestatus/user/mapper/UserMapper.java
  Server/src/main/java/com/codestatus/user/repository/UserRepository.java
  Server/src/main/java/com/codestatus/user/service/UserService.java
Labels: ✨ 기능 추가

#38 ✨ feat: jwt & oauth2 인증 추가
  .github/ISSUE_TEMPLATE/issue-task-card.md
  .gitignore
  README.md
  Server/src/main/java/com/codestatus/auth/config/SecurityConfig.java
  Server/src/main/java/com/codestatus/auth/filter/JwtAuthenticationFilter.java
  Server/src/main/java/com/codestatus/auth/filter/JwtVerificationFilter.java
  Server/src/main/java/com/codestatus/auth/handler/OAuth2MemberSuccessHandler.java
  Server/src/main/java/com/codestatus/auth/handler/OAuth2UserSuccessHandler.java
  Server/src/main/java/com/codestatus/auth/handler/UserAccessDeniedHandler.java
  Server/src/main/java/com/codestatus/auth/handler/UserAuthenticationEntryPoint.java
  Server/src/main/java/com/codestatus/auth/handler/UserAuthenticationFailureHandler.java
  Server/src/main/java/com/codestatus/auth/handler/UserAuthenticationSuccessHandler.java
  Server/src/main/java/com/codestatus/auth/jwt/JwtTokenizer.java
  Server/src/main/java/com/codestatus/auth/userdetails/UsersDetailService.java
  Server/src/main/java/com/codestatus/auth/utils/JwtResponseUtil.java
Labels: ✨ 기능 추가

#40 ✨ feat: feed & etcs.
  Server/src/main/java/com/codestatus/comment/controller/CommentController.java
  Server/src/main/java/com/codestatus/comment/dto/CommentPostDto.java
  Server/src/main/java/com/codestatus/comment/dto/CommentResponseDto.java
  Server/src/main/java/com/codestatus/comment/dto/CommnetPatchDto.java
  Server/src/main/java/com/codestatus/comment/mapper/CommentMapper.java
  Server/src/main/java/com/codestatus/comment/repository/CommentRepository.java
  Server/src/main/java/com/codestatus/comment/service/CommentService.java
  Server/src/main/java/com/codestatus/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/feed/dto/FeedPatchDto.java
  Server/src/main/java/com/codestatus/feed/dto/FeedPostDto.java
  Server/src/main/java/com/codestatus/feed/dto/FeedResponseDto.java
  Server/src/main/java/com/codestatus/feed/entity/Category.java
  Server/src/main/java/com/codestatus/feed/entity/Feed.java
  Server/src/main/java/com/codestatus/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/feed/service/FeedService.java
  Server/src/main/java/com/codestatus/hashtag/controller/HashtagController.java
  Server/src/main/java/com/codestatus/hashtag/dto/HashtagPostDto.java
  Server/src/main/java/com/codestatus/hashtag/dto/HashtagResponseDto.java
  Server/src/main/java/com/codestatus/hashtag/mapper/HashtagMapper.java
  Server/src/main/java/com/codestatus/hashtag/repository/HashtagRepository.java
  Server/src/main/java/com/codestatus/hashtag/service/HashtagService.java
  Server/src/main/java/com/codestatus/image/controller/ImageController.java
  Server/src/main/java/com/codestatus/image/dto/ImagePatchDto.java
  Server/src/main/java/com/codestatus/image/dto/ImagePostDto.java
  Server/src/main/java/com/codestatus/image/dto/ImageResponseDto.java
  Server/src/main/java/com/codestatus/image/mapper/ImageMapper.java
  Server/src/main/java/com/codestatus/image/repository/ImageRepository.java
  Server/src/main/java/com/codestatus/image/service/ImageService.java
  Server/src/main/java/com/codestatus/like/controller/LikeController.java
  Server/src/main/java/com/codestatus/like/dto/LikePatchDto.java
  Server/src/main/java/com/codestatus/like/dto/LikePostDto.java
  Server/src/main/java/com/codestatus/like/dto/LikeResponseDto.java
  Server/src/main/java/com/codestatus/like/mapper/LikeMapper.java
  Server/src/main/java/com/codestatus/like/repository/LikeRepository.java
  Server/src/main/java/com/codestatus/like/service/LikeService.java
  Server/src/main/java/com/codestatus/ranking/controller/RankingController.java
  Server/src/main/java/com/codestatus/ranking/dto/RankingPatchDto.java
  Server/src/main/java/com/codestatus/ranking/dto/RankingPostDto.java
  Server/src/main/java/com/codestatus/ranking/dto/RankingResponseDto.java
  Server/src/main/java/com/codestatus/ranking/mapper/RankingMapper.java
  Server/src/main/java/com/codestatus/ranking/repository/RankingRepository.java
  Server/src/main/java/com/codestatus/ranking/service/RankingService.java
  Server/src/main/java/com/codestatus/status/entity/Stat.java
Labels: ✨ 기능 추가

#43 ✨ feat: 유저 레벨업 기능 추가
  Server/src/main/java/com/codestatus/user/exp/Exp.java
  Server/src/main/java/com/codestatus/user/repository/ExpTableRepository.java
  Server/src/main/java/com/codestatus/user/service/UserService.java
Labels: ✨ 기능 추가

#45 ✨ feat: comment 기능 추가
  Server/build.gradle
  Server/src/main/java/com/codestatus/comment/controller/CommentController.java
  Server/src/main/java/com/codestatus/comment/dto/CommentPostDto.java
  Server/src/main/java/com/codestatus/comment/dto/CommentResponseDto.java
  Server/src/main/java/com/codestatus/comment/dto/CommnetPatchDto.java
  Server/src/main/java/com/codestatus/comment/mapper/CommentMapper.java
  Server/src/main/java/com/codestatus/comment/repository/CommentRepository.java
  Server/src/main/java/com/codestatus/comment/service/CommentService.java
  Server/src/main/java/com/codestatus/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/user/mapper/UserMapper.java
Labels: ✨ 기능 추가

#56 ♻ refactor:comment 도메인 refactoring
  Server/src/main/java/com/codestatus/domain/comment/controller/CommentController.java
  Server/src/main/java/com/codestatus/domain/comment/service/CommentService.java
Labels: ♻️ 리팩토링

#51 ✨ feat: 회원가입 페이지
  Client/src/assets/common/google-login.png
  Client/src/assets/common/kakao-login.png
  Client/src/assets/common/shield.png
  Client/src/assets/common/sword.png
  Client/src/assets/icons/hide.png
  Client/src/assets/icons/pixel-glasses.png
  Client/src/assets/icons/view.png
  Client/src/components/user/Login.tsx
  Client/src/components/user/Register.tsx
  Client/src/pages/TitlePage.tsx
  Client/src/titlebg.jpeg
Labels: ✨ 기능 추가

#58 🐛 fix: 회원가입 페이지에서 로그인 페이지 이동 버튼 수정
  Client/src/components/user/Login.tsx
  Client/src/components/user/Register.tsx
Labels: 🐛 버그 수정

#57 ✨ feat: Map 페이지 클라이언트 부분 구현
  Client/public/categoryList/0.json
  Client/public/categoryList/1.json
  Client/public/categoryList/2.json
  Client/public/categoryList/3.json
  Client/public/categoryList/4.json
  Client/src/assets/bg/map.png
  Client/src/components/map/ServerList.tsx
  Client/src/main.tsx
  Client/src/pages/MapPage.tsx
  Client/src/utility/icon.tsx
Labels: ♻️ 리팩토링, ⚙️ 설정, ✨ 기능 추가, 💄HTML/CSS

#60 ✨ feat: 스테이터스 창
  Client/package-lock.json
  Client/package.json
  Client/public/user/test.json
  Client/src/components/title/StatusChart.tsx
  Client/src/components/title/StatusListItem.tsx
  Client/src/components/title/StatusScreen.tsx
Labels: ♻️ 리팩토링, ⚙️ 설정, ✨ 기능 추가

#62 ✨ feat:get categories with stat id API 추가
  Server/src/main/java/com/codestatus/domain/category/dto/CategoryResponseDto.java
  Server/src/main/java/com/codestatus/domain/status/controller/StatController.java
  Server/src/main/java/com/codestatus/domain/status/dto/StatResponseDto.java
  Server/src/main/java/com/codestatus/domain/status/entity/Stat.java
  Server/src/main/java/com/codestatus/domain/status/mapper/StatMapper.java
  Server/src/main/java/com/codestatus/domain/status/service/StatService.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Labels: ✨ 기능 추가

#63 Feat/weeklybest
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Labels: ♻️ 리팩토링, ✨ 기능 추가

#67 ✨ feat: 사용자 로그인 창
  Client/package-lock.json
  Client/package.json
  Client/public/user/users.json
  Client/src/components/title/LoginSection.tsx
  Client/src/main.tsx
  Client/src/redux/actions/actions.js
  Client/src/redux/reducers/reducer.js
  Client/src/redux/store/store.js
Labels: ✨ 기능 추가

#69 ✨ feat: gain exp when first like
  Server/src/main/java/com/codestatus/domain/like/repository/LikeRepository.java
  Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserService.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
  Server/src/main/resources/application-server.yml
Labels: ✨ 기능 추가, 🐛 버그 수정
