Repository codestates-seb/seb45_main_022, pull requests merged in 2023-09, with the labels that each got.

#73 ✨ feat: 해쉬태그 기능 추가.
  Server/src/main/java/com/codestatus/domain/category/entity/Category.java
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/entity/Feed.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
  Server/src/main/java/com/codestatus/domain/hashTag/controller/HashTagController.java
  Server/src/main/java/com/codestatus/domain/hashTag/dto/HashTagPostDto.java
  Server/src/main/java/com/codestatus/domain/hashTag/dto/HashTagResponseDto.java
  Server/src/main/java/com/codestatus/domain/hashTag/entity/FeedHashTag.java
  Server/src/main/java/com/codestatus/domain/hashTag/entity/HashTag.java
  Server/src/main/java/com/codestatus/domain/hashTag/mapper/HashTagMapper.java
  Server/src/main/java/com/codestatus/domain/hashTag/repository/FeedHashTagRepository.java
  Server/src/main/java/com/codestatus/domain/hashTag/repository/HashTagRepository.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
  Server/src/main/java/com/codestatus/domain/hashtag/controller/HashtagController.java
  Server/src/main/java/com/codestatus/domain/hashtag/dto/HashtagPostDto.java
  Server/src/main/java/com/codestatus/domain/hashtag/mapper/HashtagMapper.java
  Server/src/main/java/com/codestatus/domain/hashtag/repository/HashtagRepository.java
  Server/src/main/java/com/codestatus/domain/hashtag/service/HashtagService.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/global/service/BaseService.java
Labels: ✨ 기능 추가

#75 ✨ feat: 회원가입 페이지 유효성 검사 수정 및 refactoring
  Client/src/api/auth.ts
  Client/src/components/title/LoginSection.tsx
  Client/src/components/title/RegisterSection.tsx
  Client/src/hooks/validation.ts
Labels: ♻️ 리팩토링, ✨ 기능 추가

#76 ♻ refactor: user service에서 level service 분리
  Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
  Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
  Server/src/main/java/com/codestatus/domain/user/service/LevelService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserService.java
Labels: ♻️ 리팩토링, ✨ 기능 추가

#77 ✨ feat: 이메일 발송 기능 추가
  Server/build.gradle
  Server/src/main/java/com/codestatus/global/mail/controller/EmailController.java
  Server/src/main/java/com/codestatus/global/mail/dto/EmailDto.java
  Server/src/main/java/com/codestatus/global/mail/entity/Email.java
  Server/src/main/java/com/codestatus/global/mail/mapper/EmailMapper.java
  Server/src/main/java/com/codestatus/global/mail/service/EmailService.java
  Server/src/main/resources/application-server.yml
Labels: ✨ 기능 추가

#79 ✨feat : 로그인 페이지 수정
  Client/src/assets/common/loadinng.gif
  Client/src/components/title/LoginSection.tsx
Labels: ♻️ 리팩토링

#81 ♻ refactor: service interface 추가
  Server/src/main/java/com/codestatus/domain/comment/controller/CommentController.java
  Server/src/main/java/com/codestatus/domain/comment/service/CommentService.java
  Server/src/main/java/com/codestatus/domain/comment/service/CommentServiceImpl.java
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
  Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
  Server/src/main/java/com/codestatus/domain/status/service/StatService.java
  Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
  Server/src/main/java/com/codestatus/domain/user/service/LevelService.java
  Server/src/main/java/com/codestatus/domain/user/service/LevelServiceImpl.java
  Server/src/main/java/com/codestatus/domain/user/service/UserService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
  Server/src/main/java/com/codestatus/global/service/BaseService.java
Labels: ♻️ 리팩토링

#82 ✨ feat: Feed 페이지 부분 구현 및 icon 배열 데이터 리팩토링
  Client/public/feed/feedData.tsx
  Client/src/api/category.ts
  Client/src/assets/feed/board.png
  Client/src/assets/feed/feedItem.png
  Client/src/assets/feed/filter_Search.png
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/Header.tsx
  Client/src/components/feed/Main.tsx
  Client/src/components/feed/SearchBar.tsx
  Client/src/components/map/ServerList.tsx
  Client/src/components/title/StatusListItem.tsx
  Client/src/main.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/pages/MapPage.tsx
  Client/src/utility/axios.js
  Client/src/utility/icon.ts
Labels: ♻️ 리팩토링, ⚙️ 설정, ✨ 기능 추가, 💄HTML/CSS, 🙋‍♂️ 리뷰 요청

#83 ♻️ refactor: 의미 없는 코드 삭제, +@RequiredArgsConstructor
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/hashTag/mapper/HashTagMapper.java
Labels: ♻️ 리팩토링

#85 ✨ feat, ♻️ refactor: feed
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
Labels: ♻️ 리팩토링, ✨ 기능 추가

#86 ♻️ refactor: 고군분투의 흔적 삭제
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/dto/HashTagResponseDto.java
  Server/src/main/java/com/codestatus/domain/hashTag/entity/FeedHashTag.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
Labels: ♻️ 리팩토링

#88 📝 docs: UserRepository 쿼리문 추가
  Server/src/main/java/com/codestatus/domain/user/repository/UserRepository.java
Labels: 📝 문서

#89 🐛 fix: feeds response 일부 수정 및 출석체크 api 일부 변경
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
  Server/src/main/java/com/codestatus/domain/user/service/LevelServiceImpl.java
Labels: 🐛 버그 수정

#90 ✨ feat: feed api 권한부여
  Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
Labels: ✨ 기능 추가

#91 🐛 fix: 유저 정보 조회 response 일부 변경
  Server/src/main/java/com/codestatus/domain/user/dto/StatusResponse.java
  Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
Labels: 🐛 버그 수정

#93 ✨ feat:feed report api 추가, email sender 추가
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/global/mail/service/EmailService.java
  Server/src/main/java/com/codestatus/global/report/controller/ReportController.java
  Server/src/main/java/com/codestatus/global/report/entity/ReportFeed.java
  Server/src/main/java/com/codestatus/global/report/reporitory/ReportFeedRepository.java
  Server/src/main/java/com/codestatus/global/report/service/ReportFeedServiceImpl.java
  Server/src/main/java/com/codestatus/global/report/service/ReportService.java
  Server/src/main/java/com/codestatus/global/utils/CustomMailSender.java
  Server/src/main/resources/application-server.yml
Labels: ✨ 기능 추가

#92 ♻️ refactor: 스테이터스 코드, 카테고리 코드 값을 통해 스테이터스, 카테고리 정보를 가져올 수 있도록 수정
  Client/public/user/test.json
  Client/src/api/user.ts
  Client/src/components/feed/Header.tsx
  Client/src/components/map/ServerList.tsx
  Client/src/components/title/StatusChart.tsx
  Client/src/components/title/StatusListItem.tsx
  Client/src/components/title/StatusScreen.tsx
  Client/src/utility/category.ts
  Client/src/utility/status.ts
Labels: ♻️ 리팩토링, 🐛 버그 수정

#94 ✨ feat: 문구로 해쉬태그 검색기능 + 해쉬태그ID로 피드 검색 추가, 해쉬태그 카운트 기능 추가
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/controller/HashTagController.java
  Server/src/main/java/com/codestatus/domain/hashTag/dto/HashTagResponseDto.java
  Server/src/main/java/com/codestatus/domain/hashTag/entity/HashTag.java
  Server/src/main/java/com/codestatus/domain/hashTag/mapper/HashTagMapper.java
  Server/src/main/java/com/codestatus/domain/hashTag/repository/HashTagRepository.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
Labels: ✨ 기능 추가

#97 ✨ feat:custom authentication provider 추가 및 ♻ refactor:RequiredArgsContsructor적용
  Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
  Server/src/main/java/com/codestatus/global/auth/filter/JwtAuthenticationFilter.java
  Server/src/main/java/com/codestatus/global/auth/filter/JwtVerificationFilter.java
  Server/src/main/java/com/codestatus/global/auth/handler/OAuth2UserSuccessHandler.java
  Server/src/main/java/com/codestatus/global/auth/provider/CustomAuthenticationProvider.java
  Server/src/main/java/com/codestatus/global/auth/userdetails/UsersDetailService.java
  Server/src/main/java/com/codestatus/global/auth/utils/JwtResponseUtil.java
Labels: ♻️ 리팩토링, ✨ 기능 추가

#101 ✨ feat: Feed 페이지 구현
  Client/public/feed/feedData.tsx
  Client/public/feed/feedData1.json
  Client/public/feed/feedData10.json
  Client/public/feed/feedData11.json
  Client/public/feed/feedData12.json
  Client/public/feed/feedData13.json
  Client/public/feed/feedData2.json
  Client/public/feed/feedData3.json
  Client/public/feed/feedData4.json
  Client/public/feed/feedData5.json
  Client/public/feed/feedData6.json
  Client/public/feed/feedData7.json
  Client/public/feed/feedData8.json
  Client/public/feed/feedData9.json
  Client/src/api/feed.ts
  Client/src/assets/feed/commentButton.png
  Client/src/assets/feed/likeButton.png
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/Header.tsx
  Client/src/components/feed/Main.tsx
  Client/src/components/feed/SearchBar.tsx
  Client/src/main.tsx
  Client/src/pages/FeedPage.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#99 ✨ feat: 이미지 업로드 모달
  Client/package-lock.json
  Client/package.json
  Client/src/assets/common/modal-frame-cropper.png
  Client/src/assets/common/no-image.png
  Client/src/components/title/ImageUploadModal.tsx
  Client/src/components/title/ProfileScreen.tsx
Labels: ⚙️ 설정, ✨ 기능 추가, 💄HTML/CSS

#95 ✨feat : 게시슬 상세 컴포턴트 및 댓글 창 컴포넌트 생성 (중간 merge)
  Client/src/api/post.ts
  Client/src/assets/common/post-frame.png
  Client/src/components/common/PostFrame.tsx
  Client/src/components/post/Comments.tsx
  Client/src/components/post/UserPost.tsx
Labels: ✨ 기능 추가, 💄HTML/CSS

#87 ✨ feat: 출석 보상 창 UI 작성 및 소소한 리팩토링
  Client/src/components/common/LoadingBar.tsx
  Client/src/components/title/AuthScreen.tsx
  Client/src/components/title/CheckInScreen.tsx
  Client/src/components/title/LoginSection.tsx
  Client/src/components/title/ProfileScreen.tsx
  Client/src/components/title/RegisterSection.tsx
  Client/src/components/title/StatusScreen.tsx
  Client/src/components/title/TitleScreen.tsx
  Client/src/pages/TitlePage.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#103 🐛 fix: deleted comment가 feed에 영향주는 오류 해결
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/dto/HashTagResponseDto.java
  Server/src/main/java/com/codestatus/domain/hashTag/entity/HashTag.java
  Server/src/main/java/com/codestatus/domain/hashTag/mapper/HashTagMapper.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
Labels: 🐛 버그 수정

#102 🐛fix:delete hashtag in feed when user resign
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Labels: 🐛 버그 수정

#104 ♻️ refactor: 일일 출석체크 기능 분리
  Server/src/main/java/com/codestatus/domain/attendance/controller/AttendanceController.java
  Server/src/main/java/com/codestatus/domain/attendance/dto/AttendanceDto.java
  Server/src/main/java/com/codestatus/domain/attendance/entity/Attendance.java
  Server/src/main/java/com/codestatus/domain/attendance/mapper/AttendanceMapper.java
  Server/src/main/java/com/codestatus/domain/attendance/repository/AttendanceRepository.java
  Server/src/main/java/com/codestatus/domain/attendance/service/AttendanceService.java
  Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
  Server/src/main/java/com/codestatus/domain/user/service/LevelServiceImpl.java
Labels: ♻️ 리팩토링

#105 ♻️ refactor: feed 작성, 검색, 수정 변경
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedPatchDto.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/entity/Feed.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Labels: ♻️ 리팩토링

#106 ♻️ refactor: React query를 사용한 커스텀 훅으로 피드 조회 리팩토링
  Client/src/components/map/ServerList.tsx
  Client/src/hooks/useFeedList.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/pages/MapPage.tsx
Labels: ♻️ 리팩토링

#107 📝 docs: dockerfile 추가
  Server/Dockerfile
  Server/src/main/resources/application-local.yml
  Server/src/main/resources/application-server.yml
  Server/src/main/resources/application.yml
Labels: 📝 문서

#108 ✨ feat: 피드 작성 모달
  Client/package-lock.json
  Client/package.json
  Client/src/assets/common/loading-image.png
  Client/src/assets/common/modal-frame-post.png
  Client/src/assets/icons/btn-pencil.png
  Client/src/components/common/ImageUploadModal.tsx
  Client/src/components/feed/FeedEditor.css
  Client/src/components/feed/FeedEditor.tsx
  Client/src/components/feed/Main.tsx
  Client/src/components/feed/PostScreen.tsx
  Client/src/components/feed/TagEditor.tsx
  Client/src/components/title/ProfileScreen.tsx
  Client/src/index.css
  Client/src/main.tsx
  Client/src/pages/FeedPage.tsx
  Client/vite.config.ts
Labels: ♻️ 리팩토링, ⚙️ 설정, ✨ 기능 추가

#110 ✨feat : 피드 리스트 페이지 수정 (게시글 팝업 이벤트, 최신순/주간 베스트순 필터 기능 추가)
  Client/public/feed/feedData1.json
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/Main.tsx
  Client/src/components/post/Comments.tsx
  Client/src/components/post/UserPost.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가, 💄HTML/CSS

#111 ✨ feat: Search 페이지 구현
  Client/.env
  Client/.env.sample
  Client/src/api/feed.ts
  Client/src/components/feed/Main.tsx
  Client/src/components/feed/SearchBar.tsx
  Client/src/hooks/useFeedList.tsx
  Client/src/main.tsx
  Client/src/pages/SearchPage.tsx
  Client/vite.config.ts
Labels: ⚙️ 설정, ✨ 기능 추가, 🐛 버그 수정

#113 ✨feat : 로그인 및 회원가입 api 성공, 토큰 local storage에 저장
  Client/.env.sample
  Client/src/api/auth.ts
  Client/src/components/title/LoginSection.tsx
  Client/src/components/title/RegisterSection.tsx
Labels: ✨ 기능 추가

#114 🐛 fix: 주간베스트 수정
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/image/controller/ImageController.java
  Server/src/main/java/com/codestatus/domain/image/service/ImageService.java
  Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
  Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
  Server/src/main/java/com/codestatus/domain/user/entity/User.java
  Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
  Server/src/main/java/com/codestatus/domain/user/repository/UserRepository.java
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
  Server/src/main/java/com/codestatus/global/report/service/ReportFeedServiceImpl.java
Labels: 🐛 버그 수정

#117 ✨ feat: Map 페이지 뒤로 가기 이미지 및 기능 추가
  Client/src/assets/common/back-button.png
  Client/src/pages/MapPage.tsx
Labels: ✨ 기능 추가

#118 ♻ refactor:공통 기능 command화
  Server/src/main/java/com/codestatus/domain/attendance/service/AttendanceService.java
  Server/src/main/java/com/codestatus/domain/comment/command/CommentCommand.java
  Server/src/main/java/com/codestatus/domain/comment/service/CommentServiceImpl.java
  Server/src/main/java/com/codestatus/domain/feed/command/FeedCommand.java
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/command/FeedHashTagCommand.java
  Server/src/main/java/com/codestatus/domain/hashTag/repository/FeedHashTagRepository.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
  Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
  Server/src/main/java/com/codestatus/domain/user/command/LevelCommand.java
  Server/src/main/java/com/codestatus/domain/user/command/UserCommand.java
  Server/src/main/java/com/codestatus/domain/user/service/LevelService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/global/report/service/ReportFeedServiceImpl.java
Labels: ♻️ 리팩토링

#119 ✨ feat: 뒤로 가기 버튼 컴포넌트로 캡슐화 및 Map & Feed 페이지에 적용
  Client/src/components/common/BackButton.tsx
  Client/src/components/feed/Header.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/pages/MapPage.tsx
Labels: ✨ 기능 추가

#120 ♻️ refactor: 전체 피드 리스트 및 주간 베스트 리스트에 API 주소 추가 및 Custom Hook 수정
  Client/src/api/feed.ts
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/Main.tsx
  Client/src/hooks/useFeedList.tsx
  Client/src/pages/FeedPage.tsx
  Client/tailwind.config.js
Labels: ♻️ 리팩토링

#123 🐛 fix: like count 수정
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
Labels: 🐛 버그 수정

#122 ✨ feat: 비밀번호 변경 + @
  Client/src/api/user.ts
  Client/src/components/common/Button.tsx
  Client/src/components/main/ChangePwTab.tsx
  Client/src/components/main/ProfileScreen.tsx
  Client/src/utility/axios.ts
Labels: ♻️ 리팩토링, ⚙️ 설정, ✨ 기능 추가, 🐛 버그 수정

#125 🐛 fix: get weekly best with native query ♻ refactor: delete unnecessary lines in local profile
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/resources/application-local.yml
Labels: ♻️ 리팩토링, 🐛 버그 수정

#124 ✨ 전체 피드 조회 (최신순, 주간 베스트)
  Client/src/api/feed.ts
  Client/src/components/feed/BestFeedItem.tsx
  Client/src/components/feed/LatestFeedItem.tsx
  Client/src/components/feed/Main.tsx
  Client/src/hooks/useFeedList.tsx
  Client/src/hooks/useUserFeed.tsx
  Client/src/pages/FeedPage.tsx
  Client/tailwind.config.js
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#126 ✨ feat: 프로필 이미지 변경; Button 컴포넌트 리팩토링
  Client/src/api/user.ts
  Client/src/assets/common/no-image.png
  Client/src/components/common/Button.tsx
  Client/src/components/common/ImageUploadModal.tsx
  Client/src/components/main/ProfileScreen.tsx
  Client/src/utility/image.ts
Labels: ♻️ 리팩토링, ✨ 기능 추가

#128 ✨ feat: 닉네임 변경
  Client/src/api/user.ts
  Client/src/components/common/ImageUploadModal.tsx
  Client/src/components/main/ProfileHeader.tsx
  Client/src/components/main/ProfileScreen.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#127 ✨ feat: 리액트 쿼리 useMutation을 이용하여 피드 작성 기능 구현
  Client/src/api/post.ts
  Client/src/components/feed/Main.tsx
  Client/src/components/feed/PostScreen.tsx
  Client/src/hooks/usePost.tsx
Labels: ✨ 기능 추가, 🐛 버그 수정

#129 ✨ feat: my-post api 추가
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
Labels: ✨ 기능 추가

#130 ✨ feat: add errorCode in error response, 🐛fix: add NoArgsConstructor in Comment post Dto
  Server/src/main/java/com/codestatus/domain/comment/dto/CommentPostDto.java
  Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
  Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
  Server/src/main/java/com/codestatus/global/advice/GlobalExceptionAdvice.java
  Server/src/main/java/com/codestatus/global/auth/handler/UserAuthenticationFailureHandler.java
  Server/src/main/java/com/codestatus/global/auth/utils/ErrorResponseSender.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
  Server/src/main/java/com/codestatus/global/response/ErrorResponse.java
  Server/src/main/java/com/codestatus/global/response/ValidationErrorResponse.java
Labels: ✨ 기능 추가, 🐛 버그 수정

#132 ✨feat : 상세 게시글 api 연동
  Client/package-lock.json
  Client/package.json
  Client/src/api/feed.ts
  Client/src/components/feed/BestFeedItem.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/LatestFeedItem.tsx
  Client/src/components/feed/Main.tsx
  Client/src/components/post/Comments.tsx
  Client/src/components/post/UserPost.tsx
  Client/src/hooks/useUserFeed.tsx
  Client/src/pages/FeedPage.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#133 ✨ feat: 카테고리 내 특정 키워드의 해쉬태그를 포함한 feed 검색 api 추가
  Server/src/main/java/com/codestatus/domain/comment/command/CommentCommand.java
  Server/src/main/java/com/codestatus/domain/comment/repository/CommentRepository.java
  Server/src/main/java/com/codestatus/domain/feed/command/FeedCommand.java
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Labels: ✨ 기능 추가, 🐛 버그 수정

#137 ✨feat : 상세 피드 디자인 변경, 댓글 추가 기능
  Client/src/api/comment.ts
  Client/src/components/feed/LatestFeedItem.tsx
  Client/src/components/post/Comments.tsx
  Client/src/components/post/UserPost.tsx
  Client/src/hooks/useComment.tsx
Labels: ✨ 기능 추가, 💄HTML/CSS

#139 ♻️ refactor: 에러 핸들링 리팩토링; 회원가입 에러 메시지 표시 수정
  Client/src/api/auth.ts
  Client/src/api/error.ts
  Client/src/components/auth/RegisterSection.tsx
  Client/src/components/main/ProfileHeader.tsx
  Client/src/components/main/ProfileScreen.tsx
  Client/src/components/main/StatusScreen.tsx
  Client/src/hooks/usePostFeedMutation.tsx
  Client/src/hooks/useRegister.tsx
  Client/src/hooks/useRegisterMutation.tsx
  Client/src/hooks/useUserInfo.tsx
  Client/src/hooks/useUserInfoQuery.tsx
  Client/src/pages/AuthPage.tsx
  Client/src/pages/PrivateRoute.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#140 ✨ feat: Feed 페이지 무한 스크롤 기능 추가
  Client/src/api/feed.ts
  Client/src/components/common/BackButton.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/Header.tsx
  Client/src/components/feed/Main.tsx
  Client/src/hooks/useFeedList.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/utility/scrollUtils.ts
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#141 🐛 fix: 타임존 설정 추가
  Server/Dockerfile
  Server/src/main/java/com/codestatus/CodeStateMainProjectApplication.java
Labels: 🐛 버그 수정

#142 ♻️ refactor: 피드 조회 페이지 무한 스크롤 리팩토링
  Client/src/api/feed.ts
  Client/src/components/common/BackButton.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/Header.tsx
  Client/src/components/feed/Main.tsx
  Client/src/hooks/useFeedList.tsx
  Client/src/hooks/useFeedListQuery.tsx
  Client/src/hooks/useInfiniteScroll.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/utility/scrollUtils.ts
Labels: ♻️ 리팩토링

#143 🐛 fix: 피드 작성 시 피드 조회 페이지 피드 리스트 즉시 업데이트 하도록 수정
  Client/src/hooks/usePostFeedMutation.tsx
Labels: 🐛 버그 수정

#145 ✨ feat: 검색 타입 별 검색 기능
  Client/src/api/feed.ts
  Client/src/components/feed/FeedListWrapper.tsx
  Client/src/components/feed/FilterButton.tsx
  Client/src/components/feed/SearchBar.tsx
  Client/src/components/feed/SearchedFeedListWrapper.tsx
  Client/src/hooks/useFeedListQuery.tsx
  Client/src/hooks/useSearch.tsx
  Client/src/main.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/pages/SearchPage.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#144 🐛 fix: add jwtException when refresh token doesn't exist
  Server/src/main/java/com/codestatus/global/auth/filter/JwtVerificationFilter.java
  Server/src/main/java/com/codestatus/global/auth/handler/UserAuthenticationEntryPoint.java
Labels: 🐛 버그 수정

#147 💄 design: SearchBar 디자인 변경
  Client/src/api/feed.ts
  Client/src/assets/feed/clickedSearchBar.png
  Client/src/assets/feed/searchBar.png
  Client/src/components/feed/LatestFeedItem.tsx
  Client/src/components/feed/SearchBar.tsx
  Client/tailwind.config.js
Labels: 🐛 버그 수정, 💄HTML/CSS

#148 ✨feat: 상세 페이지 댓글 수정 및 삭제 기능, 상세 페이지 내용 수정 및 삭제
  Client/src/api/comment.ts
  Client/src/api/editFeed.ts
  Client/src/components/post/Comments.tsx
  Client/src/components/post/UserPost.tsx
  Client/src/hooks/useComment.tsx
Labels: ✨ 기능 추가

#151 ⚙️ refactor: 피드 수정 기능
  Client/src/api/feed.ts
  Client/src/components/feed-detail/FeedContentSection.tsx
Labels: ♻️ 리팩토링

#153 ✨ feat: 피드 수정 기능 추가 + @
  Client/src/api/feed.ts
  Client/src/components/feed-detail/CommentSection.tsx
  Client/src/components/feed-detail/FeedContentEditSection.tsx
  Client/src/components/feed-detail/FeedContentSection.tsx
  Client/src/components/feed-detail/FeedDetailModal.tsx
  Client/src/components/feed/FeedEditor.css
  Client/src/components/feed/FeedEditor.tsx
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/FeedList.tsx
  Client/src/components/feed/PostScreen.tsx
  Client/src/components/feed/SearchResult.tsx
  Client/src/components/feed/TagEditor.tsx
  Client/src/hooks/usePatchFeedMutation.tsx
  Client/src/main.tsx
Labels: ✨ 기능 추가

#154 🐛 fix: access token 재발급 수정, ✨ feat: jwt 인증 오류 error response 세분화
  Server/src/main/java/com/codestatus/global/auth/filter/JwtVerificationFilter.java
  Server/src/main/java/com/codestatus/global/auth/handler/UserAuthenticationEntryPoint.java
  Server/src/main/java/com/codestatus/global/auth/utils/ErrorResponseSender.java
  Server/src/main/java/com/codestatus/global/auth/utils/JwtResponseUtil.java
  Server/src/main/java/com/codestatus/global/exception/AccessTokenExpiredException.java
  Server/src/main/java/com/codestatus/global/exception/RefreshTokenExpiredException.java
  Server/src/main/java/com/codestatus/global/response/ErrorResponse.java
  Server/src/main/java/com/codestatus/global/response/JwtErrorResponse.java
Labels: ✨ 기능 추가, 🐛 버그 수정

#155 ✨ feat: 출석 체크 기능
  Client/src/api/error.ts
  Client/src/api/user.ts
  Client/src/components/main/CheckInScreen.tsx
  Client/src/hooks/useCheckInQuery.tsx
  Client/src/pages/MainPage.tsx
Labels: ✨ 기능 추가, 🐛 버그 수정

#156 ✨feat : 마이페이지, 나의 피드 리스트
  Client/src/api/userFeed.ts
  Client/src/components/main/ProfileScreen.tsx
  Client/src/hooks/useUserFeedListQuery.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#158 ✨ feat: Header에 로그인한 개인 유저 정보를 연동 & 클릭 시, 모달창 노출하는 기능 추가
  Client/src/components/feed-detail/FeedDetailModal.tsx
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/FeedList.tsx
  Client/src/components/feed/Header.tsx
  Client/src/components/feed/SearchResult.tsx
  Client/src/components/main/ProfileScreen.tsx
  Client/src/components/main/StatusScreen.tsx
  Client/src/pages/FeedPage.tsx
  Client/src/pages/SearchPage.tsx
Labels: ✨ 기능 추가, 🐛 버그 수정, 💄HTML/CSS

#161 ✨ feat: add kakao oauth2 login
  Server/src/main/java/com/codestatus/global/auth/handler/OAuth2UserSuccessHandler.java
  Server/src/main/resources/application.yml
Labels: ✨ 기능 추가

#162 ✨ feat: Feed 상세 페이지에 좋아요 기능 추가 & 좋아요 로직 `Api`와 `Hook`으로 분리 리팩토링
  Client/src/api/feed.ts
  Client/src/api/like.ts
  Client/src/components/feed-detail/FeedContentSection.tsx
  Client/src/components/feed/FeedItem.tsx
  Client/src/hooks/useLikeMutation.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#166 ✨ feat: get comment list api 외 10개
  Server/src/main/java/com/codestatus/domain/category/entity/Category.java
  Server/src/main/java/com/codestatus/domain/comment/controller/CommentController.java
  Server/src/main/java/com/codestatus/domain/comment/entity/Comment.java
  Server/src/main/java/com/codestatus/domain/comment/mapper/CommentMapper.java
  Server/src/main/java/com/codestatus/domain/comment/repository/CommentRepository.java
  Server/src/main/java/com/codestatus/domain/comment/service/CommentService.java
  Server/src/main/java/com/codestatus/domain/comment/service/CommentServiceImpl.java
  Server/src/main/java/com/codestatus/domain/feed/command/FeedCommand.java
  Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
  Server/src/main/java/com/codestatus/domain/feed/dto/FeedResponseDto.java
  Server/src/main/java/com/codestatus/domain/feed/entity/Feed.java
  Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
  Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
  Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
  Server/src/main/java/com/codestatus/domain/hashTag/command/FeedHashTagCommand.java
  Server/src/main/java/com/codestatus/domain/hashTag/entity/FeedHashTag.java
  Server/src/main/java/com/codestatus/domain/hashTag/repository/FeedHashTagRepository.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
  Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
  Server/src/main/java/com/codestatus/domain/image/entity/Image.java
  Server/src/main/java/com/codestatus/domain/like/entity/Like.java
  Server/src/main/java/com/codestatus/domain/like/likeCommand/LikeCommand.java
  Server/src/main/java/com/codestatus/domain/like/repository/LikeRepository.java
  Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
  Server/src/main/java/com/codestatus/domain/like/service/LikeServiceImpl.java
  Server/src/main/java/com/codestatus/domain/ranking/entity/Ranking.java
  Server/src/main/java/com/codestatus/domain/status/entity/Status.java
  Server/src/main/java/com/codestatus/domain/user/entity/User.java
  Server/src/main/java/com/codestatus/global/auth/provider/CustomAuthenticationProvider.java
  Server/src/main/java/com/codestatus/global/report/entity/ReportFeed.java
  Server/src/main/resources/application.yml
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#164 ✨feat : 회원탈퇴 구현
  Client/src/api/user.ts
  Client/src/assets/common/reaper.png
  Client/src/components/main/DeleteScreen.tsx
  Client/src/components/main/ProfileHeader.tsx
  Client/src/components/main/ProfileScreen.tsx
  Client/src/components/main/UserFeedsTab.tsx
  Client/src/hooks/useDeleteUserMutation.tsx
Labels: ✨ 기능 추가

#167 ✨ feat: 코멘트 API 변경에 따른 코드 수정 및 무한 스크롤 적용
  Client/src/api/comment.ts
  Client/src/api/feed.ts
  Client/src/components/feed-detail/CommentItem.tsx
  Client/src/components/feed-detail/CommentSection.tsx
  Client/src/hooks/useCommentListQuery.tsx
  Client/src/hooks/usePostCommentMutation.tsx
Labels: ✨ 기능 추가, 🐛 버그 수정

#171 🐛 fix: get user status on custom user details
  Server/src/main/java/com/codestatus/global/auth/userdetails/UsersDetailService.java
Labels: 🐛 버그 수정

#169 ♻️ refactor: 커스텀 훅 리팩토링
  Client/package-lock.json
  Client/package.json
  Client/src/api/user.ts
  Client/src/components/auth/LoginSection.tsx
  Client/src/components/auth/RegisterSection.tsx
  Client/src/components/feed-detail/CommentSection.tsx
  Client/src/components/feed-detail/FeedContentEditSection.tsx
  Client/src/components/feed-detail/FeedContentSection.tsx
  Client/src/components/feed-detail/FeedDetailModal.tsx
  Client/src/components/feed/FeedItem.tsx
  Client/src/components/feed/PostScreen.tsx
  Client/src/components/main/CheckInScreen.tsx
  Client/src/components/main/DeleteScreen.tsx
  Client/src/hooks/useCheckInQuery.tsx
  Client/src/hooks/useCommentListQuery.tsx
  Client/src/hooks/useCommentPostMutation.tsx
  Client/src/hooks/useDeleteUserMutation.tsx
  Client/src/hooks/useFeedDetailQuery.tsx
  Client/src/hooks/useFeedListQuery.tsx
  Client/src/hooks/useFeedPatchMutation.tsx
  Client/src/hooks/useFeedPostMutation.tsx
  Client/src/hooks/useLikeMutation.tsx
  Client/src/hooks/useLoginMutation.tsx
  Client/src/hooks/usePatchFeedMutation.tsx
  Client/src/hooks/usePostCommentMutation.tsx
  Client/src/hooks/usePostFeedMutation.tsx
  Client/src/hooks/useRegisterMutation.tsx
  Client/src/hooks/useUserDeleteMutation.tsx
  Client/src/hooks/useUserFeedListQuery.tsx
  Client/src/hooks/useUserInfoQuery.tsx
  Client/src/main.tsx
  Client/src/pages/CheckInPage.tsx
  Client/src/pages/MainPage.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#172 🐛 fix: 재가입 user 처리
  Server/src/main/java/com/codestatus/domain/status/command/StatusCommand.java
  Server/src/main/java/com/codestatus/domain/status/repository/StatusRepository.java
  Server/src/main/java/com/codestatus/domain/user/entity/User.java
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Labels: 🐛 버그 수정

#173 ✨ feat: 404 페이지 이미지 변경 & 아무 곳이나 클릭 시, 홈으로 이동하는 기능 추가
  Client/src/assets/bg/404.gif
  Client/src/pages/NotFoundPage.tsx
Labels: ✨ 기능 추가, 💄HTML/CSS

#178 ✨ feat: 유저 프로필 이미지 초기화 기능 추가
  Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
  Server/src/main/java/com/codestatus/domain/user/service/UserService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
  Server/src/main/java/com/codestatus/global/aws/FileStorageService.java
  Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Labels: ✨ 기능 추가, 🐛 버그 수정

#181 🐛fix: oauth2 인증 외
  Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
  Server/src/main/java/com/codestatus/domain/user/repository/UserRepository.java
  Server/src/main/java/com/codestatus/domain/user/service/UserService.java
  Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
  Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
  Server/src/main/java/com/codestatus/global/auth/handler/OAuth2UserSuccessHandler.java
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정
